# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: elt_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'elt_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65lt_service.proto\x12\neltservice\"D\n\x17ListRepositoriesRequest\x12\x13\n\x0bname_filter\x18\x01 \x01(\t\x12\x14\n\x0cprivate_only\x18\x02 \x01(\x08\"S\n\nRepository\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07private\x18\x04 \x01(\x08\"H\n\x18ListRepositoriesResponse\x12,\n\x0crepositories\x18\x01 \x03(\x0b\x32\x16.eltservice.Repository\"<\n!GetRepositoryAccessDetailsRequest\x12\x17\n\x0frepository_name\x18\x01 \x01(\t\"@\n\x0c\x41\x63\x63\x65ssDetail\x12\x14\n\x0cuser_or_team\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"N\n\"GetRepositoryAccessDetailsResponse\x12(\n\x06\x61\x63\x63\x65ss\x18\x01 \x03(\x0b\x32\x18.eltservice.AccessDetail\",\n\x15\x45valuatePolicyRequest\x12\x13\n\x0bpolicy_name\x18\x01 \x01(\t\"4\n\x0fPolicyViolation\x12\x0e\n\x06\x65ntity\x18\x01 \x01(\t\x12\x11\n\tviolation\x18\x02 \x01(\t\"I\n\x16\x45valuatePolicyResponse\x12/\n\nviolations\x18\x01 \x03(\x0b\x32\x1b.eltservice.PolicyViolation2\xc1\x02\n\nELTService\x12]\n\x10ListRepositories\x12#.eltservice.ListRepositoriesRequest\x1a$.eltservice.ListRepositoriesResponse\x12{\n\x1aGetRepositoryAccessDetails\x12-.eltservice.GetRepositoryAccessDetailsRequest\x1a..eltservice.GetRepositoryAccessDetailsResponse\x12W\n\x0e\x45valuatePolicy\x12!.eltservice.EvaluatePolicyRequest\x1a\".eltservice.EvaluatePolicyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'elt_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTREPOSITORIESREQUEST']._serialized_start=33
  _globals['_LISTREPOSITORIESREQUEST']._serialized_end=101
  _globals['_REPOSITORY']._serialized_start=103
  _globals['_REPOSITORY']._serialized_end=186
  _globals['_LISTREPOSITORIESRESPONSE']._serialized_start=188
  _globals['_LISTREPOSITORIESRESPONSE']._serialized_end=260
  _globals['_GETREPOSITORYACCESSDETAILSREQUEST']._serialized_start=262
  _globals['_GETREPOSITORYACCESSDETAILSREQUEST']._serialized_end=322
  _globals['_ACCESSDETAIL']._serialized_start=324
  _globals['_ACCESSDETAIL']._serialized_end=388
  _globals['_GETREPOSITORYACCESSDETAILSRESPONSE']._serialized_start=390
  _globals['_GETREPOSITORYACCESSDETAILSRESPONSE']._serialized_end=468
  _globals['_EVALUATEPOLICYREQUEST']._serialized_start=470
  _globals['_EVALUATEPOLICYREQUEST']._serialized_end=514
  _globals['_POLICYVIOLATION']._serialized_start=516
  _globals['_POLICYVIOLATION']._serialized_end=568
  _globals['_EVALUATEPOLICYRESPONSE']._serialized_start=570
  _globals['_EVALUATEPOLICYRESPONSE']._serialized_end=643
  _globals['_ELTSERVICE']._serialized_start=646
  _globals['_ELTSERVICE']._serialized_end=967
# @@protoc_insertion_point(module_scope)
