# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import elt_service_pb2 as elt__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in elt_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ELTServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRepositories = channel.unary_unary(
                '/eltservice.ELTService/ListRepositories',
                request_serializer=elt__service__pb2.ListRepositoriesRequest.SerializeToString,
                response_deserializer=elt__service__pb2.ListRepositoriesResponse.FromString,
                _registered_method=True)
        self.GetRepositoryAccessDetails = channel.unary_unary(
                '/eltservice.ELTService/GetRepositoryAccessDetails',
                request_serializer=elt__service__pb2.GetRepositoryAccessDetailsRequest.SerializeToString,
                response_deserializer=elt__service__pb2.GetRepositoryAccessDetailsResponse.FromString,
                _registered_method=True)
        self.EvaluatePolicy = channel.unary_unary(
                '/eltservice.ELTService/EvaluatePolicy',
                request_serializer=elt__service__pb2.EvaluatePolicyRequest.SerializeToString,
                response_deserializer=elt__service__pb2.EvaluatePolicyResponse.FromString,
                _registered_method=True)


class ELTServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListRepositories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRepositoryAccessDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ELTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRepositories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRepositories,
                    request_deserializer=elt__service__pb2.ListRepositoriesRequest.FromString,
                    response_serializer=elt__service__pb2.ListRepositoriesResponse.SerializeToString,
            ),
            'GetRepositoryAccessDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRepositoryAccessDetails,
                    request_deserializer=elt__service__pb2.GetRepositoryAccessDetailsRequest.FromString,
                    response_serializer=elt__service__pb2.GetRepositoryAccessDetailsResponse.SerializeToString,
            ),
            'EvaluatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluatePolicy,
                    request_deserializer=elt__service__pb2.EvaluatePolicyRequest.FromString,
                    response_serializer=elt__service__pb2.EvaluatePolicyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eltservice.ELTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eltservice.ELTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ELTService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListRepositories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eltservice.ELTService/ListRepositories',
            elt__service__pb2.ListRepositoriesRequest.SerializeToString,
            elt__service__pb2.ListRepositoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRepositoryAccessDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eltservice.ELTService/GetRepositoryAccessDetails',
            elt__service__pb2.GetRepositoryAccessDetailsRequest.SerializeToString,
            elt__service__pb2.GetRepositoryAccessDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eltservice.ELTService/EvaluatePolicy',
            elt__service__pb2.EvaluatePolicyRequest.SerializeToString,
            elt__service__pb2.EvaluatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
